# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: rvdata
  pool: 5
  host: localhost
  username: catherine
  password: ejhsm7tp
  
production:
  adapter: postgresql
  encoding: unicode
  database: rvdata
  pool: 5
  host: localhost
  username: catherine
  password: ejhsm7tp